Адаптивная сетка главной страницы
htmlacademy-adaptive/887399-sedona-21 pull request #10
Opened 2020-12-13 09:13 UTC by ratroian

2020-12-13 15:38 UTC, kosovych requested changes

2020-12-13 15:38 UTC, kosovych commented on source/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
![image](https://user-images.githubusercontent.com/19348382/102016151-20bbbe00-3d68-11eb-9550-1d6ef93a204c.png)
мобайл

2020-12-13 15:38 UTC, kosovych commented on source/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
![image](https://user-images.githubusercontent.com/19348382/102016331-15b55d80-3d69-11eb-9ae6-cd17c57b1466.png)

таблет

2020-12-13 15:38 UTC, kosovych commented on source/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
для десктопа добавь обертку для всего контента, максимальная ширина которой будет 1200, отцентрирован и с тенью как на макете (см. макет)

2020-12-13 15:38 UTC, kosovych commented on source/sass/blocks/benefits.scss
> +  }
не нужно хардкодить ширину, у тебя фоны упираются в края, значит должны тянутся

2020-12-13 15:38 UTC, kosovych commented on source/sass/blocks/benefits.scss
> +  // }
удали закоментированый код (по всему проекту)

2020-12-13 15:38 UTC, kosovych commented on source/sass/blocks/main-nav.scss
> +    width: 1200px;
ненужно хардкодить ширину

2020-12-13 15:38 UTC, kosovych commented on source/sass/blocks/selection.scss
> +  background-color: #ffffff;
у тебя есть файл с цветами

2020-12-13 15:38 UTC, kosovych commented on source/sass/blocks/title.scss
> +  }
зачем переопределять одно и то же

2020-12-13 15:38 UTC, kosovych commented on source/sass/global/viewports.scss
> +$mobile-width-only: 767px;
эта переменная нигде не используется, она тебе точно нужна?

2020-12-16 22:53 UTC, ratroian commented on source/sass/global/viewports.scss
> +$mobile-width-only: 767px;
наверное нет

2020-12-16 22:53 UTC, ratroian commented on source/sass/blocks/title.scss
> +  }
сразу неправильно понял суть. исправил

2020-12-16 22:53 UTC, ratroian commented on source/sass/blocks/selection.scss
> +  background-color: #ffffff;
ок, понял

2020-12-16 22:54 UTC, ratroian commented on source/sass/blocks/main-nav.scss
> +    width: 1200px;
ок

2020-12-16 22:54 UTC, ratroian commented on source/sass/blocks/benefits.scss
> +  // }
ок

2020-12-16 22:54 UTC, ratroian commented on source/sass/blocks/benefits.scss
> +  }
ок

2020-12-16 22:54 UTC, ratroian commented on source/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
попробовал

2020-12-17 20:13 UTC, kosovych commented on source/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
теперь отцентрируй эту обертку 
![image](https://user-images.githubusercontent.com/19348382/102538551-16295d80-40b5-11eb-9947-3e98c118d0cc.png)

2020-12-17 20:23 UTC, kosovych requested changes

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/page-header.scss
> +    flex-direction: row;
эти стили уже есть у .main-nav

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/main-nav.scss
> +  }
`display: none;` дважды переопределяешь

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/site-list.scss
> +  }
```
    display: flex;
    flex-direction: row;
    justify-content: space-between;
```
дваждый одно и то же переопределяешь

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/hero.scss
> +}
одно и то же

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/title.scss
> +    align-items: center;
для этого селектора уже есть `align-items: center;` ты даром его перезаписуешь

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/services-list.scss
> +    display: flex;
display: flex; есть уже на мобилке

2020-12-17 20:23 UTC, kosovych commented on source/sass/blocks/benefits-item.scss
> +}
дубль

2020-12-20 19:34 UTC, ratroian commented on source/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
сделал, добавил фон

2020-12-20 19:42 UTC, ratroian commented on source/sass/blocks/page-header.scss
> +    flex-direction: row;
поправил

2020-12-20 19:47 UTC, ratroian commented on source/sass/blocks/main-nav.scss
> +  }
поправил

2020-12-20 19:48 UTC, ratroian commented on source/sass/blocks/site-list.scss
> +  }
поправил

2020-12-20 19:50 UTC, ratroian commented on source/sass/blocks/hero.scss
> +}
понял

2020-12-20 20:05 UTC, ratroian commented on source/sass/blocks/title.scss
> +    align-items: center;
ок

2020-12-20 20:06 UTC, ratroian commented on source/sass/blocks/benefits-item.scss
> +}
удалил

2020-12-21 18:41 UTC, kosovych commented on source/sass/blocks/site-list.scss
> +  }
`display: flex;` для `.site-list ` даром переопределяешь все ровно

2020-12-21 18:44 UTC, merged