Module5 task1
htmlacademy-adaptive/887399-sedona-21 pull request #13
Opened 2021-01-14 10:30 UTC by ratroian

2021-01-14 19:14 UTC, kosovych requested changes

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104636453-0ef17180-56ac-11eb-8d7b-b0ad29e21cdf.png)
для первого пункта добавь модификатор, который увеличит его высоту (1), а так же отрисует белый треугольник (псевдоэлемент)

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104636748-81fae800-56ac-11eb-919e-8cb3e31fa7d0.png)
можно br добавить

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104637015-e1f18e80-56ac-11eb-81c4-b68dbf7e1b72.png)

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104637084-f6358b80-56ac-11eb-8e0f-a813191b2b0c.png)
десктоп

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104637131-0c434c00-56ad-11eb-8739-7f4688ba1d7a.png)

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104637281-43196200-56ad-11eb-9ddd-81e312432840.png)
это все ссылка, добавь интерактивность

2021-01-14 19:14 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104637359-5e846d00-56ad-11eb-87b9-054988a15291.png)
проверь ховер и нажатие

2021-01-15 10:57 UTC, ratroian commented on source/index.html
>        <header class="page-header">
исправил

2021-01-15 12:09 UTC, ratroian commented on source/index.html
>        <header class="page-header">
исправил

2021-01-15 14:03 UTC, ratroian commented on source/index.html
>        <header class="page-header">
переделал

2021-01-15 14:03 UTC, ratroian commented on source/index.html
>        <header class="page-header">
добавил

2021-01-15 14:47 UTC, ratroian commented on source/index.html
>        <header class="page-header">
сделал как смог)

2021-01-15 14:47 UTC, ratroian commented on source/index.html
>        <header class="page-header">
поправил

2021-01-15 14:47 UTC, ratroian commented on source/index.html
>        <header class="page-header">
поправил

2021-01-16 07:37 UTC, kosovych commented on source/index.html
>        <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104806198-67289080-57de-11eb-9204-d49450854c5b.png)
![image](https://user-images.githubusercontent.com/19348382/104806202-760f4300-57de-11eb-835d-0005a5d1835d.png)

2021-01-16 07:42 UTC, kosovych commented on source/index.html
>        <header class="page-header">
.copyright - это сслыка

2021-01-16 15:46 UTC, merged