Module5 task2
htmlacademy-adaptive/887399-sedona-21 pull request #14
Opened 2021-01-19 23:59 UTC by ratroian

2021-01-20 15:43 UTC, kosovych requested changes

2021-01-20 15:43 UTC, kosovych commented on source/form.html
> +        <a class="popup__button--succes button">ЗАКРЫТЬ ОКНО</a>
модификатор opup__button--succes без элемета

2021-01-20 15:43 UTC, kosovych commented on source/form.html
> +      <a class="popup__button popup-fail__button button">OK</a>
popup-fail__title popup-fail__text popup-fail__button элементы блока без Блока

2021-01-20 15:43 UTC, kosovych commented on source/form.html
>                <label class="radio__label" for="filter-positive">Скорее положительное</label>
![image](https://user-images.githubusercontent.com/19348382/105196522-64ae9980-5b44-11eb-8fb9-76bc050f2e8a.png)
не надо рисовать на css, используй SVG. На крайний случай div или span с микросеткой 
![image](https://user-images.githubusercontent.com/19348382/105196896-c3741300-5b44-11eb-8746-6a8d3c8379fe.png)

2021-01-20 15:43 UTC, kosovych commented on source/form.html
> +            <h3 class="form-location__title form-heading form-heading--checkbox form-heading--delimiter">Посещенные<br> достопримечательности:</h3>
![image](https://user-images.githubusercontent.com/19348382/105197220-0c2bcc00-5b45-11eb-9f6a-0542881bef48.png)

2021-01-20 15:43 UTC, kosovych commented on source/form.html
> +            <h3 class="form-location__title form-heading form-heading--checkbox form-heading--delimiter">Посещенные<br> достопримечательности:</h3>
![image](https://user-images.githubusercontent.com/19348382/105197995-e3580680-5b45-11eb-83f0-bef9fc16d5a1.png)

2021-01-20 15:43 UTC, kosovych commented on source/form.html
> -                <a class="social__link social__link--twitter" href="#">twitter</a>
чего футер из index.html не перетащить?

2021-01-20 15:43 UTC, kosovych commented on source/form.html
>                <label class="radio__label" for="filter-positive">Скорее положительное</label>
тоже самое с чекбоксами

2021-01-20 15:43 UTC, kosovych commented on source/form.html
>                <textarea class="textarea__input" name="massage" id="massage-field" placeholder="В свободной форме">Опишите подробно все свои восторги</textarea>
![image](https://user-images.githubusercontent.com/19348382/105198493-62e5d580-5b46-11eb-82f5-f84f8e4e1dab.png)
чтоб не ломалась верстка разреши растягивать только по вертикали

2021-01-21 14:26 UTC, ratroian commented on source/form.html
> +        <a class="popup__button--succes button">ЗАКРЫТЬ ОКНО</a>
исправил

2021-01-21 14:27 UTC, ratroian commented on source/form.html
> +      <a class="popup__button popup-fail__button button">OK</a>
Исправил

2021-01-21 20:57 UTC, ratroian commented on source/form.html
> +            <h3 class="form-location__title form-heading form-heading--checkbox form-heading--delimiter">Посещенные<br> достопримечательности:</h3>
исправил

2021-01-21 20:57 UTC, ratroian commented on source/form.html
> -                <a class="social__link social__link--twitter" href="#">twitter</a>
исправил

2021-01-21 21:01 UTC, ratroian commented on source/form.html
>                <textarea class="textarea__input" name="massage" id="massage-field" placeholder="В свободной форме">Опишите подробно все свои восторги</textarea>
исправил

2021-01-22 15:15 UTC, kosovych commented on source/form.html
> -                <a class="social__link social__link--twitter" href="#">twitter</a>
@ratroian  не исправил. ссылка в футере на сайт академии не интерактивна

2021-01-22 15:23 UTC, kosovych requested changes

2021-01-22 15:23 UTC, kosovych commented on source/form.html
> +            <h3 class="form-comment__title form-heading form-heading--delimiter">Опишите свои эмоции:</h3>
![image](https://user-images.githubusercontent.com/19348382/105508976-b0447d00-5cd5-11eb-881a-47e0f1b7c7e6.png)

2021-01-22 15:23 UTC, kosovych commented on source/form.html
> +            <h3 class="form-comment__title form-heading form-heading--delimiter">Опишите свои эмоции:</h3>
![image](https://user-images.githubusercontent.com/19348382/105509070-cce0b500-5cd5-11eb-8404-8420473f9ed2.png)

2021-01-22 15:23 UTC, kosovych commented on source/sass/blocks/form-heading.scss
> +  padding: 0;
зачет ставишь `padding: 0;`? они так 0. и так по всему проекту

2021-01-22 15:23 UTC, kosovych commented on source/form.html
> +                </div>
https://www.loom.com/share/0522eb0cf78f450bbe1df20f8ddbfcd7 при взаимодействии с элементом он не должен так менять свой размеры (дергаться)

2021-01-23 11:08 UTC, ratroian commented on source/form.html
> -                <a class="social__link social__link--twitter" href="#">twitter</a>
Исправлено

2021-01-23 12:01 UTC, ratroian commented on source/form.html
> +            <h3 class="form-comment__title form-heading form-heading--delimiter">Опишите свои эмоции:</h3>
исправил

2021-01-23 12:01 UTC, ratroian commented on source/form.html
> +            <h3 class="form-comment__title form-heading form-heading--delimiter">Опишите свои эмоции:</h3>
+

2021-01-23 12:01 UTC, ratroian commented on source/sass/blocks/form-heading.scss
> +  padding: 0;
Перестраховка, наверное)

2021-01-23 12:37 UTC, ratroian commented on source/sass/blocks/form-heading.scss
> +  padding: 0;
Почистил

2021-01-23 12:45 UTC, ratroian commented on source/form.html
> +                </div>
Исправил

2021-01-23 14:47 UTC, merged