Module6 task1
htmlacademy-adaptive/887399-sedona-21 pull request #16
Opened 2021-01-24 19:15 UTC by ratroian

2021-01-24 20:00 UTC, kosovych requested changes

2021-01-25 10:50 UTC, ratroian commented on source/catalog.html
>          </div>
ок

2021-01-25 10:50 UTC, ratroian commented on source/catalog.html
>          </div>
исправил

2021-01-25 10:51 UTC, ratroian commented on source/catalog.html
>          </div>
ок

2021-01-25 11:05 UTC, ratroian commented on source/sass/blocks/hero.scss
> +    @media (min-resolution: 2dppx) {
ok

2021-01-25 14:02 UTC, merged