Добавил спрайты, изображения webp
htmlacademy-adaptive/887399-sedona-21 pull request #17
Opened 2021-01-25 18:52 UTC by ratroian

2021-01-26 06:51 UTC, kosovych requested changes

2021-01-26 06:51 UTC, kosovych commented on source/sass/blocks/checkbox.scss
> +// }
удали весь закоментированый код в SCSS

2021-01-26 06:51 UTC, kosovych commented on source/form.html
> +    </svg> -->
удали весь закоvtнтированный код с HTML

2021-01-26 06:51 UTC, kosovych commented on source/form.html
>    <body class="page__body">
![image](https://user-images.githubusercontent.com/19348382/105810039-ef631e80-5fb2-11eb-8709-4fef44fce69d.png)
тебе нужна эта папка? если да - назови ее правильно

2021-01-26 06:51 UTC, kosovych commented on source/form.html
>            </svg>
лого тип должен быть кадрированным изображением с 2мя картинками (через `<picture>`)

2021-01-26 06:53 UTC, kosovych requested changes
Проверь код `npm run test` и исправь ошибки

2021-01-26 17:29 UTC, ratroian commented on source/sass/blocks/checkbox.scss
> +// }
Почистил

2021-01-26 17:29 UTC, ratroian commented on source/form.html
> +    </svg> -->
Почистил

2021-01-26 17:31 UTC, ratroian commented on source/form.html
>    <body class="page__body">
Временная. Удалил

2021-01-26 23:54 UTC, ratroian commented on source/form.html
>            </svg>
Поправил

2021-01-27 06:36 UTC, kosovych reviewed
Б1. Выполнена HTML-разметка всех страниц проекта и всех элементов на этих страницах.
- модальные окна должны быть спозиционированы по цетнтру вьюпорта и скрыты

Б5. Отсутствуют типовые ошибки в разметке по методологии.
- проверь страницы в https://yoksel.github.io/html-tree/

Б7. В CSS отсутствует !important.

- для visually-hidden оставь коментарий зачем там important

2021-01-27 10:03 UTC, merged