Разметка главной
htmlacademy-adaptive/887399-sedona-21 pull request #2
Opened 2020-11-16 18:37 UTC by ratroian

2020-11-17 13:58 UTC, kosovych requested changes

2020-11-17 13:58 UTC, kosovych commented on source/index.html
> +            </dl>
это подсписок для пункта "НАСТОЯЩИЙ ГОРОДОК"

2020-11-17 13:58 UTC, kosovych commented on source/index.html
> +        <b>Разработано <a href="#">HTML Academy</a></b>
добавь href https://up.htmlacademy.ru/adaptive/21/project/sedona#sedona-3-9

2020-11-19 21:59 UTC, kosovych requested changes
1. Проверь валидность HTML сдесьhttps://validator.w3.org/nu/#textarea
2. Проверь свой БЭМ здесь https://yoksel.github.io/html-tree/
3. Форму по разделам разбей с помощью fieldset

2020-11-19 21:59 UTC, kosovych commented on source/catalog.html
> +          <ul class="main-nav__list site-list">\
убери слэш в конце

2020-11-19 21:59 UTC, kosovych commented on source/catalog.html
> +            <li class="site-list__item--active"><a href="">Главная</a></li>
не может быть модификатор без элемента

2020-11-19 21:59 UTC, kosovych commented on source/index.html
> +      <div class="title__wrapper">
элемент без блока

2020-11-19 21:59 UTC, kosovych commented on source/index.html
> +        <img class="title__image" src="" alt="Welcome to Sedona" width="" height="">
тоже самое

2020-11-19 21:59 UTC, kosovych commented on source/index.html
> +              <p class="content__intro">Седона не артакцион для туристов, там течет своя жизнь</p>
Элементы без блока

2020-11-19 21:59 UTC, kosovych commented on source/index.html
> +              <li class="benefits__item">
элементы без блока

2020-11-19 21:59 UTC, kosovych commented on source/index.html
> +              <p class="content__intro">Да, по нему можно пройти! Если вы осмелитесь, конечно</p>
элементы без блока

2020-11-19 21:59 UTC, kosovych commented on source/index.html
> +              <p class="content__intro">Ехать в Седону из Лас-Вегаса совсем не скучно!</p>
тоже самое

2020-11-19 21:59 UTC, kosovych commented on source/form.html
> +            <label class="" for="username">Имя*:</label>
зачем пустой класс?

2020-11-19 21:59 UTC, kosovych commented on source/form.html
> +            <input type="tel" name="tel" pattern="[0-9]{1}-[0-9]{3}-[0-9]{3}" required>
id забыл

2020-11-19 21:59 UTC, kosovych commented on source/form.html
> +        <div class="form__element">
fieldset?

2020-11-19 21:59 UTC, kosovych commented on source/catalog.html
> +          </div>
а количество лайков?

2020-11-22 18:19 UTC, ratroian commented on source/catalog.html
> +          <ul class="main-nav__list site-list">\
ок

2020-11-23 20:40 UTC, closed without merging