БЭМ главная, каталог, форма
htmlacademy-adaptive/887399-sedona-21 pull request #3
Opened 2020-11-23 20:20 UTC by ratroian

2020-11-23 21:16 UTC, kosovych requested changes

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +          </div>
эти инпуты и label выглядят абсолтно одинаково, зачем им разные классы?

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +          <h3 class="form-contact__title">Ваше общее впечатление:</h3>
проверь заголовок

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +          </div>
проверь это блок, порядок не тот и label не совпадают

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +          </div>
инпуты выглядат так же как и в "Представьтесь", значить Блоки это одни и те же, но с модификаторами

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +          <h3 class="form-contact__title">Ваше общее впечатление:</h3>
все заголовки с формы одинаковые, значит это один и тот же элемент

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +        <input class="form__element form-button button" type="submit" value="Отправить">
используй `<button>`

2020-11-23 21:16 UTC, kosovych commented on source/index.html
> +        <ul class="benefits__list">
есть нумерация, значит `<ol>`

2020-11-23 21:16 UTC, kosovych commented on source/index.html
> +                <span class="services-text">Еда</span>
h4

2020-11-23 21:16 UTC, kosovych commented on source/index.html
> +        <a href="" class="button-button">Найти гостиницу</a>
button-button?) масло маслянное)

2020-11-23 21:16 UTC, kosovych commented on source/form.html
> +        <input class="form__element form-button button" type="submit" value="Отправить">
у тебя уже есть такая же кнопка на index, значит должен быть один и тот же Блок

2020-11-23 21:44 UTC, ratroian commented on source/catalog.html
> +        <li class="gallery__item gallery-article">
ok

2020-11-23 21:48 UTC, ratroian commented on source/catalog.html
> +            <button class="like-meter__button">Clcc</button>
ok

2020-11-23 21:49 UTC, ratroian commented on source/catalog.html
> +            <button class="like-meter__button">Clcc</button>
ok

2020-11-23 22:03 UTC, ratroian commented on source/form.html
> +          </div>
не нужны

2020-11-23 22:05 UTC, ratroian commented on source/form.html
> +          <h3 class="form-contact__title">Ваше общее впечатление:</h3>
ок

2020-11-23 22:07 UTC, ratroian commented on source/form.html
> +          <h3 class="form-fullname__title">Контактная информация:</h3>
ок

2020-11-23 22:11 UTC, ratroian commented on source/form.html
> +          </div>
ок

2020-11-23 22:19 UTC, ratroian commented on source/form.html
> +          <h3 class="form-contact__title">Ваше общее впечатление:</h3>
ok

2020-11-23 22:20 UTC, ratroian commented on source/form.html
> +        <input class="form__element form-button button" type="submit" value="Отправить">
ok

2020-11-23 22:22 UTC, ratroian commented on source/index.html
> +        <ul class="benefits__list">
ok

2020-11-23 22:24 UTC, ratroian commented on source/index.html
> +                <span class="services-text">Еда</span>
ok

2020-11-23 22:25 UTC, ratroian commented on source/index.html
> +        <a href="" class="button-button">Найти гостиницу</a>
ok

2020-11-23 22:27 UTC, ratroian commented on source/form.html
> +        <input class="form__element form-button button" type="submit" value="Отправить">
ok

2020-11-23 22:41 UTC, ratroian commented on source/form.html
> +          </div>
ok

2020-11-24 18:15 UTC, ratroian commented on source/catalog.html
> +        </div>
ок

2020-11-24 19:59 UTC, kosovych commented on source/form.html
> +          </div>
не исправлено, разбей на блоки инпуты

2020-11-24 20:00 UTC, kosovych commented on source/form.html
> +          </div>
![image](https://user-images.githubusercontent.com/19348382/100145080-76572600-2ea0-11eb-8125-e156f10cafb8.png)

2020-11-24 20:01 UTC, kosovych commented on source/form.html
> +          </div>
не исправлено, обсудили

2020-11-24 20:02 UTC, kosovych commented on source/form.html
> +          <h3 class="form-contact__title">Ваше общее впечатление:</h3>
не исправлено, разные элементы, а должны быть одинаковыми (могут быть модификаторы)

2020-11-24 20:13 UTC, kosovych requested changes

2020-11-24 20:13 UTC, kosovych commented on source/form.html
> +        <button class="form__element form-button button" type="submit" value="Отправить">ОТПРАВИТЬ ОТЗЫВ</button>
сдесь не нужно 2 блока

2020-11-24 20:13 UTC, kosovych commented on source/index.html
> +            </div>
это элементы для блока benefits__item (тебе нужно его сделать блоком, но он может быть и элементом одновременно)

2020-11-24 20:13 UTC, kosovych commented on source/index.html
> +              </li>
блок в элементами

2020-11-24 20:13 UTC, kosovych commented on source/index.html
> +      <div class="page-footer wrapper">
2 одинаковых блока внутри друг друга

2020-11-24 20:13 UTC, kosovych commented on source/catalog.html
> +      <p class="gallery-intro">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о политике и экономике.</p>
на каждой странице есть блок с текстом и заголовком, вынеси их в отдельный блок

2020-11-25 22:07 UTC, ratroian commented on source/form.html
> +          </div>
plus

2020-11-25 22:11 UTC, ratroian commented on source/form.html
> +          </div>
Исправил

2020-11-25 22:14 UTC, ratroian commented on source/form.html
> +          <h3 class="form-contact__title">Ваше общее впечатление:</h3>
хм, у меня в файле исправлено
ок, поправил)

2020-11-25 22:15 UTC, ratroian commented on source/form.html
> +        <button class="form__element form-button button" type="submit" value="Отправить">ОТПРАВИТЬ ОТЗЫВ</button>
поправил
оставил баттон

2020-11-25 22:40 UTC, ratroian commented on source/index.html
> +            </div>
Ну, вроде поправил. На сколько понял

2020-11-25 22:43 UTC, ratroian commented on source/index.html
> +              </li>
поправил

2020-11-25 22:46 UTC, ratroian commented on source/index.html
> +      <div class="page-footer wrapper">
Исправил, сделал как элемент

2020-11-25 22:58 UTC, ratroian commented on source/catalog.html
> +      <p class="gallery-intro">Не можете решиться на путешествие из-за курса? Фотографии помогут вам забыть о политике и экономике.</p>
ok

2020-11-26 08:03 UTC, kosovych commented on source/form.html
> +          </div>
@ratroian странный нейминг для инпутов `contact-info`, очень спецефичный, я бы заменил просто на input или form-field

2020-11-26 08:10 UTC, kosovych requested changes

2020-11-26 08:10 UTC, kosovych commented on source/catalog.html
> +      </div>
```
div.title
    h2.title__header
    p.title__text
```

2020-11-26 18:58 UTC, merged